apiVersion: v2
dependencies:
- name: eric-oss-network-assurance-search
  repository: https://arm.seli.gic.ericsson.se/artifactory/proj-eric-oss-drop-helm
  version: 0.2.0-160
- alias: eric-oss-network-assurance-search-rbac-proxy
  name: eric-bss-kube-rbac-proxy
  repository: https://arm.epk.ericsson.se/artifactory/proj-bam-released-helm/
  version: 1.36.0+5
- condition: eric-log-shipper.enabled
  import-values:
  - child: logShipper.config
    parent: global.logShipper.config
  name: eric-log-shipper
  repository: https://arm.sero.gic.ericsson.se/artifactory/proj-adp-gs-all-helm/
  version: 14.5.0+9
- condition: stubs.enabled
  name: eric-oss-indexer-stub
  repository: https://arm.seli.gic.ericsson.se/artifactory/proj-eric-oss-drop-helm/
  version: 1.0.2-1
description: Ericsson Assurance Visualization
name: eric-assurance-visualization
version: 1.1.0-82
