# #
# # COPYRIGHT Ericsson 2022
# #
# #
# #
# # The copyright to the computer program(s) herein is the property of
# #
# # Ericsson Inc. The programs may be used and/or copied only with written
# #
# # permission from Ericsson Inc. or in accordance with the terms and
# #
# # conditions stipulated in the agreement/contract under which the
# #
# # program(s) have been supplied.
# #
# # The explanation of role-binding file is described in docs/role-binding.md
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: {{ template "eric-assurance-visualization.name" . }}-gas-patcher-namespaced-binding
  labels:
    {{- include "eric-assurance-visualization.labels" .| nindent 4 }}
  annotations:
    {{- include "eric-assurance-visualization.helm-annotations" .| nindent 4 }}
roleRef:
  kind: Role
  name: {{ template "eric-assurance-visualization.release.name" . }}-gas-patcher-policy
  apiGroup: rbac.authorization.k8s.io
subjects:
  - kind: ServiceAccount
    name: {{ template "eric-assurance-visualization.name" . }}-gas-patcher-sa